### ISSUE TITLE
Enhacement

### ISSUE THREAD

**Issue by remusv** [d3vilh/openvpn-aws#1]
Would that be possible to be able to create new users for the UI interface with certains permissions?

**Comment by d3vilh** [comment]
Hi @remusv 
Yes it is possible with `0.9.2` OpenVPN-UI release which is on the way.
In short you can have Administrators and regular users. [Here is new functionality description](https://github.com/d3vilh/openvpn-ui#user-management).

**Comment by d3vilh** [comment]
[It is included](https://github.com/d3vilh/openvpn-aws#user-management) now into the main branch.
Closing this issue now.
