### ISSUE TITLE
Incorrect volume mount path in docker compose file

### ISSUE THREAD

**Issue by slavikss14** [d3vilh/openvpn-aws#12]
Hi, d3vilh!

Please replace following line in **templates/openvpn-docker-compose.yml.j2**:
- ./db:/opt/openvpn-gui/db
 with:
- ./db:/opt/openvpn-ui/db

Дякую!

**Comment by d3vilh** [comment]
Виправлено. @slavikss14 дуже дякую за репорт друже! ✊
